#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          astrid
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start astrid at boot time
# Description:       Enable astrid (simple continuous integration server) services.
### END INIT INFO

PIDFILE="/tmp/astrid.pid"
case "$1" in
        start)
                if [ -f $PIDFILE ] ; then
                    echo "Already running."
                    exit 1
                else                
                    echo "Starting astrid."
                    su -c "export PYTHONPATH=\"/home/koutny/local/lib/python\"; python /home/koutny/scripts/cis/start.py $PIDFILE;" koutny
                fi
                ;;
        stop)
                if [ -f $PIDFILE ] ; then
                    echo "Stopping astrid."
                    kill -9 $(cat $PIDFILE)
                    rm -f $PIDFILE
                else
                    echo "Not running."
                    exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/astrid {start|stop}"
                exit 1
                ;;
esac

exit 0
