#!/bin/sh
#/etc/init.d/atrid

PIDFILE="/tmp/astrid.pid"
case "$1" in
        start)
                echo "Starting atrid."
                su -c "export PYTHONPATH=\"/home/koutny/local/lib/python\"; python /home/koutny/scripts/cis/start.py $PIDFILE;" koutny
                ;;
        stop)
                if [ -f $PIDFILE ] ; then
                    kill -9 $(cat $PIDFILE)
                else
                    echo "Not running."
                    exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/astrid {start|stop}"
                exit 1
                ;;
esac

exit 0
