version: '3'

services:
  astrid:
    image: ghcr.io/fykosak/astrid:master
    restart: on-failure:3
    container_name: astrid
    environment:
      TZ: 'Europe/Prague'
    privileged: true # needed for containers
    volumes:
      - ./config:/home/astrid/.astrid
      - ./ssh:/home/astrid/.ssh
      - ./containers:/home/astrid/.local/share/containers
      - ./repos:/data/repos
    user: 1000:1000 # expects the main user with uid:pid
